# Generated by Django 3.2.23 on 2023-11-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20231122_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='No img', upload_to='userprofile/'),
        ),
    ]
