# Generated by Django 3.2.23 on 2023-12-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, default="{% static 'images/no-product-img.png' %}", upload_to='userprofile/'),
        ),
    ]
