# Generated by Django 3.2.23 on 2023-12-05 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_form',
            options={'verbose_name': 'Contact Form'},
        ),
        migrations.AddField(
            model_name='contact_form',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
