# Generated by Django 3.2.23 on 2023-12-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20231205_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_form',
            name='reason',
            field=models.CharField(choices=[('order', 'Order Tracking'), ('order', 'Order Issue'), ('general', 'General Query'), ('complaint', 'Complaint'), ('return', 'Return Request')], max_length=15),
        ),
    ]
