# Generated by Django 3.2.23 on 2023-12-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_subscribedusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribedusers',
            name='name',
        ),
    ]
