# Generated by Django 3.2.23 on 2023-12-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productimage_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deal',
            field=models.BooleanField(default=False),
        ),
    ]
